name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          use_pyproject: true
      - name: Setup Python 
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint==3.2.7 mypy==1.11.2
      - name: Run Pylint
        run: |
          pylint $(git ls-files "*.py")
      - name: Run Mypy
        run: |
          mypy $(git ls-files "*.py")
